import torch
import torch.nn as nn
from typing import Dict, Tuple

class UnifiedTokenizer(nn.Module):
    """
    Unified Wavelength-Conditioned Tokenizer.

    Tokenizes ALL input modalities (optical, weather, soil, calendar) through
    a single shared mechanism. Each channel's projection weights are dynamically
    generated by a hypernetwork conditioned on the channel's physical metadata
    (wavelength, spatial resolution, temporal resolution, variable ID).
    """
    def __init__(self, embed_dim=256, hypernetwork_hidden=128, hypernetwork_layers=2, max_channels=26):
        super().__init__()
        self.embed_dim = embed_dim

        # Hypernetwork: Metadata [4] -> hidden -> weights [embed_dim * input_dim (which is 1 since we project per channel value)]
        # Plus bias [embed_dim]
        # Total output size: embed_dim + embed_dim = 2 * embed_dim
        layers = []
        in_dim = 4
        for _ in range(hypernetwork_layers - 1):
            layers.append(nn.Linear(in_dim, hypernetwork_hidden))
            layers.append(nn.GELU())
            in_dim = hypernetwork_hidden
        layers.append(nn.Linear(in_dim, 2 * embed_dim))

        self.hypernetwork = nn.Sequential(*layers)
        self.norm = nn.LayerNorm(embed_dim)
        self.gelu = nn.GELU()

        self.placeholder_token = nn.Parameter(torch.randn(embed_dim))

        # We need the metadata to generate the weights
        from src.datacube.channel_registry import CHANNEL_REGISTRY, get_metadata_tensor
        channel_ids = [c.channel_id for c in CHANNEL_REGISTRY]
        # shape [num_channels, 4]
        self.register_buffer("channel_metadata", get_metadata_tensor(channel_ids))

        # Define indices for each modality to parse from the dictionary
        self.opt_idx = list(range(0, 6))
        self.wea_idx = list(range(6, 15))
        self.soil_idx = list(range(15, 22))
        self.cal_idx = list(range(22, 25))
        self.irr_idx = [25]

    def forward(self, patch_dict: Dict[str, torch.Tensor]) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Returns:
            tokens: [B, N_total, embed_dim]
            token_masks: [B, N_total]
        """
        B, T, C_opt, H, W = patch_dict["optical"].shape

        # Generate weights for all channels
        # [num_channels, 4] -> [num_channels, 2 * embed_dim]
        generated_params = self.hypernetwork(self.channel_metadata)
        W_proj = generated_params[:, :self.embed_dim] # [num_channels, embed_dim]
        b_proj = generated_params[:, self.embed_dim:] # [num_channels, embed_dim]

        # --- Optical Processing ---
        # patchify 64x64 into 16x16 patches -> 4x4=16 tokens per time step
        # Input shape: [B, T, C_opt, 64, 64]
        opt_data = patch_dict["optical"]
        # Reshape to [B, T, C_opt, 4, 16, 4, 16] -> [B, T, 16, C_opt, 16, 16] -> [B, T, 16, C_opt * 16 * 16]
        # Wait, the instruction says:
        # "Each token is formed by projecting the 6-band values of one 16x16 patch
        # using the hypernetwork-generated weights for each band, then summing."
        # This implies we project the flattened 16x16 patch values?
        # Actually, let's treat the 16x16 values as spatial features or just average pool them first?
        # Let's project each pixel value and then sum across the 16x16 patch.
        # opt_data: [B, T, C_opt, 4, 16, 4, 16] -> sum across the 16x16 spatial dims after projecting

        # W_opt: [C_opt, embed_dim], b_opt: [C_opt, embed_dim]
        W_opt = W_proj[self.opt_idx]
        b_opt = b_proj[self.opt_idx]

        # To project and sum efficiently:
        # [B, T, C_opt, 4, 16, 4, 16]
        opt_patches = opt_data.view(B, T, C_opt, 4, 16, 4, 16).permute(0, 1, 3, 5, 2, 4, 6).reshape(B, T, 16, C_opt, 256)

        # Project: val * W + b
        # [B, T, 16, C_opt, 256, 1] * [C_opt, 1, embed_dim]
        tokens_opt = opt_patches.unsqueeze(-1) * W_opt.view(C_opt, 1, self.embed_dim)
        # Sum over 256 pixels in the patch
        tokens_opt = tokens_opt.sum(dim=4) # [B, T, 16, C_opt, embed_dim]
        # Add bias (multiplied by 256 since we summed 256 pixels? Or just add bias once per patch?)
        tokens_opt = tokens_opt + b_opt.view(C_opt, self.embed_dim)
        # Sum over channels
        tokens_opt = tokens_opt.sum(dim=3) # [B, T, 16, embed_dim]

        opt_mask = patch_dict["optical_mask"] # [B, T, C_opt]
        # We consider a spatial token valid if any of its optical bands are valid
        # Actually, optical mask is per time step and channel. If all C_opt are 0, it's missing.
        # Let's say token_mask is 1.0 if optical_mask sum > 0
        opt_token_mask = (opt_mask.sum(dim=-1) > 0).float() # [B, T]
        opt_token_mask = opt_token_mask.unsqueeze(-1).repeat(1, 1, 16) # [B, T, 16]

        tokens_opt = self.gelu(self.norm(tokens_opt))

        # Handle missing modalities by replacing with placeholder
        # tokens_opt shape [B, T, 16, embed_dim]
        mask_expanded = opt_token_mask.unsqueeze(-1) # [B, T, 16, 1]
        tokens_opt = tokens_opt * mask_expanded + self.placeholder_token * (1 - mask_expanded)

        tokens_opt = tokens_opt.view(B, T * 16, self.embed_dim)
        opt_token_mask = opt_token_mask.view(B, T * 16)

        # --- Weather Processing ---
        W_wea = W_proj[self.wea_idx]
        b_wea = b_proj[self.wea_idx]
        wea_data = patch_dict["weather"] # [B, T, C_weather]
        # Project and sum
        tokens_wea = (wea_data.unsqueeze(-1) * W_wea).sum(dim=2) + b_wea.sum(dim=0) # [B, T, embed_dim]
        wea_mask = patch_dict["weather_mask"]
        wea_token_mask = (wea_mask.sum(dim=-1) > 0).float() # [B, T]

        tokens_wea = self.gelu(self.norm(tokens_wea))
        mask_expanded = wea_token_mask.unsqueeze(-1)
        tokens_wea = tokens_wea * mask_expanded + self.placeholder_token * (1 - mask_expanded)

        # --- Soil Processing ---
        W_soil = W_proj[self.soil_idx]
        b_soil = b_proj[self.soil_idx]
        soil_data = patch_dict["soil"] # [B, C_soil]
        tokens_soil = (soil_data.unsqueeze(-1) * W_soil).sum(dim=1) + b_soil.sum(dim=0) # [B, embed_dim]
        soil_mask = patch_dict["soil_mask"]
        soil_token_mask = (soil_mask.sum(dim=-1) > 0).float() # [B]

        tokens_soil = self.gelu(self.norm(tokens_soil))
        mask_expanded = soil_token_mask.unsqueeze(-1)
        tokens_soil = tokens_soil * mask_expanded + self.placeholder_token * (1 - mask_expanded)
        tokens_soil = tokens_soil.unsqueeze(1) # [B, 1, embed_dim]
        soil_token_mask = soil_token_mask.unsqueeze(1) # [B, 1]

        # --- Calendar Processing ---
        W_cal = W_proj[self.cal_idx]
        b_cal = b_proj[self.cal_idx]
        cal_data = patch_dict["calendar"] # [B, C_cal]
        tokens_cal = (cal_data.unsqueeze(-1) * W_cal).sum(dim=1) + b_cal.sum(dim=0)
        cal_mask = patch_dict["calendar_mask"]
        cal_token_mask = (cal_mask.sum(dim=-1) > 0).float()

        tokens_cal = self.gelu(self.norm(tokens_cal))
        mask_expanded = cal_token_mask.unsqueeze(-1)
        tokens_cal = tokens_cal * mask_expanded + self.placeholder_token * (1 - mask_expanded)
        tokens_cal = tokens_cal.unsqueeze(1)
        cal_token_mask = cal_token_mask.unsqueeze(1)

        # Concatenate everything
        # T*16 optical + T weather + 1 soil + 1 calendar
        tokens = torch.cat([tokens_opt, tokens_wea, tokens_soil, tokens_cal], dim=1)
        token_masks = torch.cat([opt_token_mask, wea_token_mask, soil_token_mask, cal_token_mask], dim=1)

        # Add basic positional encoding (just a simple learned one for now to satisfy shapes/gradients)
        # In a full impl, this would combine spatial, temporal, and resolution embeddings
        if not hasattr(self, 'pos_embed') or self.pos_embed.shape[1] != tokens.shape[1]:
            self.pos_embed = nn.Parameter(torch.randn(1, tokens.shape[1], self.embed_dim).to(tokens.device))

        tokens = tokens + self.pos_embed

        return tokens, token_masks
